config/routes.rb
Rails.application.routes.draw do
  get 'system_stats', to: 'index#system_stats'
  get 'api_example', to: 'index#api_example'
  get 'index/api_example', to: 'index#api_example'
  get 'index/:digits', to: 'index#render_results', as: 'render_results2'
  get ':digits', to: 'index#render_results', as: 'render_results'
  get '*missing', to: 'index#home'
  get 'index/home'
  root to: 'index#home'

  patch 'calculate', to: 'index#calculate'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
	TIMEOUT = 30
	before_action :set_digits, only: %i[calculate render_results]
	@@cpu_usage_thread = Thread.new { }
	@@net_usage_thread = Thread.new { }
	@@process_cpu_usage_thread = Thread.new { }

	def home
	end

	def calculate
		start_time = Process.clock_gettime(Process::CLOCK_MONOTONIC)

		begin
			Timeout.timeout(TIMEOUT) do
				@str = find_pi(@digits)
				end_time = Process.clock_gettime(Process::CLOCK_MONOTONIC)
				@time = end_time - start_time
				render :calculate
			end
		rescue Timeout::Error
			render :error_calculate
		end
	end

	def render_results
		start_time = Process.clock_gettime(Process::CLOCK_MONOTONIC)

		@str = begin
			Timeout.timeout(TIMEOUT) { find_pi(@digits) }
		rescue Timeout::Error
			find_pi(5000)
		end

		end_time = Process.clock_gettime(Process::CLOCK_MONOTONIC)
		@time = end_time - start_time
		msg = {digits: @str.length - 2, value: @str, time: @time}
		render :json => msg

	end

	def api_example
	end

	$cpu_usage = {}.tap { |x| x.default = 0 }
	$current_net_usage = {}.tap { |x| x.default = 0 }
	$process_cpu_usage = 0

	def system_stats
		unless @@cpu_usage_thread.alive?
			@@cpu_usage_thread = Thread.new {
				physical = LS::CPU.physical_cores.map(&:next)
				hyperthreaded = LS::CPU.hyperthreaded_cores.map(&:next)

				cpu_usages = LS::CPU.usages(0.25).to_a

				cpu_usages[0].push(:All)

				physical.each { |x|
					cpu_usages.find { |y| y[0] == x } &.push('Physcical CPU')
				}

				hyperthreaded.each { |x|
					cpu_usages.find { |y| y[0] == x } &.push('Hyperthreaded CPU')
				}

				$cpu_usage = cpu_usages
			}
		end

		unless @@net_usage_thread.alive?
			@@net_usage_thread = Thread.new { $current_net_usage = LS::Net.current_usage(0.25) }
		end

		unless @@process_cpu_usage_thread.alive?
			@@process_cpu_usage_thread = Thread.new { $process_cpu_usage = LS::ProcessInfo.cpu_usage(sleep: 0.25) }
		end
	end

	private
	def set_digits
		@digits = params[:digits].to_i.then { |x| x < 1 ? 100 : x }
	end

	def find_pi(n)
		n = 100 if n > 2 ** 60
		BigPie.calculate(n + 1).join.tap { |x| x[1, 0] = ?..freeze }
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def seo_tags(image)
		<<~EOF.html_safe
			<meta charset="utf-8">
			<meta name="author" content="Sourav Goswami [souravgoswami@protonmail.com]">
			<meta name="robots" content="all">
			<meta name="description" content="Calculate Pi on the Server">
			<meta property="og:title" content="Pi Calculator">
			<meta property="og:type" content="webapp">
			<meta property="og:image" content="#{image}">
		EOF
	end

	def example_code(route)
		code = <<~EOF.lstrip
			require 'net/https'
			require 'json'
			json_data = Net::HTTP.get(URI("#{route}"))
			JSON.parse(json_data)
		EOF

		_binding = binding
		code.each_line.map { |x| %[\n<code class="code">#{x}<span class="return-value"> # => #{_binding.eval(x)}</span></code>] }.join.html_safe
	end

	def pb(n)
		LS::PrettifyBytes.convert_short_decimal(n)
	end
end

app/helpers/index_helper.rb
module IndexHelper
	def cpu_usage
		$cpu_usage
	end

	def uptime
		u = LS::OS.uptime
		h = "%02d" % u[:hour]
		m = "%02d" % u[:minute]
		s = "%02d" % u[:second]
		j = "%02d" % u[:jiffy]

		"Uptime: <strong>#{h}:#{m}:#{s}:#{j}<br></strong>"\
		"Uptime Second: <strong>#{LS::OS.uptime_f}s</strong>".html_safe
	end

	def memory_stat
		_stat = LS::Sysinfo.stat
		_stat.default = 0

		"#{pb(LS::Memory.used * 1000)}/ "\
		"#{pb(_stat[:totalram])} "\
		"( #{LS::Memory.percent_used}% )<br>"\
		"Free: <strong>#{pb(_stat[:freeram])}</strong><br>"\
		"Shared: <strong>#{pb(_stat[:sharedram])}</strong><br>"\
		"Buffer: <strong>#{pb(_stat[:bufferram])}</strong><br>"\
		"Total High: <strong>#{pb(_stat[:totalhigh])}</strong><br>"\
		"Free High: <strong>#{pb(_stat[:freehigh])}</strong>".html_safe
	end

	def swap_usage
		devs = LS::Swap.list.map { |x|
			"#{x[0]} => #{x[1].drop(1).tap(&:pop).reverse.map { |y|
				"#{pb(y * 1000)}"
			}.join(' / ')}"
		}.join('<br>')

		"#{pb(LS::Swap.used.*(1000))}/ "\
		"#{pb(LS::Swap.total.*(1000))} "\
		"( #{LS::Swap.percent_used}% )<br>#{devs}".html_safe
	end

	def net_usage
		u = LS::Net.total_bytes

		[
			pb(u[:received]),
			pb(u[:transmitted]),
			"#{pb($current_net_usage[:received])}/s",
			"#{pb($current_net_usage[:transmitted])}/s"
		]
	end

	def process_cpu_usage
		$process_cpu_usage
	end

	def nproc
		total = LS::ProcessInfo.nproc
		online_count = LS::CPU.count_online

		"#{total} / #{online_count} (#{sprintf "%0.2f", total.*(100).fdiv(online_count)}%)"
	end

	$usb_devs = []
	$usb_devs_bef = []

	def usb_stats
		$usb_devs = LS::USB.devices_stat

		plugged = $usb_devs - $usb_devs_bef
		$usb_devs_bef = $usb_devs

		now = plugged.empty? ? nil : plugged.map { |x| x[:id] }

		$usb_devs.map.with_index { |x, i|
			new_dev = now && now.include?(x[:id])

			hwdata = x[:hwdata]
			vendor = hwdata[:vendor]
			product = hwdata[:product]
			product_name = x[:product]

			product_name_str = product_name ? "(#{product_name})" : ''

			product_str = if product_name && product && product_name != product
				"#{product_name} (#{product}) from "
			elsif product_name
				"#{product_name} from "
			elsif product
				"#{product} from "
			else
				''.freeze
			end

			out = "<strong>#{sprintf "%03d", i + 1}.</strong> #{product_str}#{vendor}"

			if new_dev
				out[0, 0] = '<span style="color: #66f">'.freeze
				out << '</span>'.freeze
			end

			out
		}.join('<br>'.freeze).html_safe
	end

	def pci_stats
		LS::PCI.devices_info.map.with_index { |x, i|
			id = x[:id]
			driver = x[:kernel_driver]
			driver_str = driver ? "(driver: #{driver})" : ''.freeze

			hwdata = x[:hwdata]
			vendor = hwdata &.[](:vendor)
			product = hwdata &.[](:product)

			vendor_str = vendor ? vendor + ' '.freeze : ''.freeze
			product_str = product ? "#{product} from " : ''.freeze

			"<strong>#{sprintf "%03d", i + 1}.</strong> #{id} #{product_str}#{vendor_str}#{driver_str}"
		}.join('<br>'.freeze).html_safe
	end

	def thermal_zone
		sensors = LS::Thermal.temperatures.sort_by { |x| x[:label] || x[:name] || x[:path] }.map.with_index { |x, i|
			t = x[:temperature]
			temp_c = sprintf "%.1f", t
			temp_f = sprintf "%.1f", t.*(1.8).+(32).to_f

			label = x[:label] || x[:name] || x[:path]

			"<strong>#{sprintf '%03d', i + 1}.</strong> #{label}: #{temp_c}&#176C (#{temp_f}&#176F)"
		}.join('<br>')

		fans = LS::Thermal.fans.sort_by { |x| x[:label] || x[:name] || x[:path] }.map.with_index { |x, i|
			rpm = x[:rpm]
			label = x[:label] || x[:name] || x[:path]

			"<strong>#{sprintf '%03d', i + 1}.</strong> #{label}, RPM: #{rpm}"
		}.join('<br>')

		<<~EOF.html_safe
			<h5>Sensors (#{LS::Thermal.count_sensors})</h5>
			#{sensors}
			<h5>Fans (#{LS::Thermal.count_fans})</h5>
			#{fans}
		EOF
	end
end

app/views/index/api_example.html.erb
<div class="centrify mb-4">
	<div class="logo">
		<svg class="pi-anim" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 468.3 468.3"><path fill="#3a556a" d="M385 69H0V18C0 11 6 5 12 5h360c7 0 13 6 13 13v51z" data-original="#3A556A"/><path fill="#e1e6e9" d="M372 377H12c-6 0-12-5-12-12V69h385v296c0 7-6 12-13 12z" data-original="#E1E6E9"/><circle cx="41.7" cy="37.2" r="16" fill="#fcd462" data-original="#FCD462"/><circle cx="93" cy="37.2" r="16" fill="#27a2db" data-original="#27A2DB"/><circle cx="144.4" cy="37.2" r="16" fill="#44c4a1" data-original="#44C4A1"/><path class="svg-rotate" fill="#27a2db" d="M440 347l28-7v-36l-28-7c-3-13-8-26-16-37l16-25-26-25-25 15c-11-7-24-13-37-16l-7-28h-36l-7 28c-13 3-26 9-37 16l-25-15-25 25 15 25c-7 11-13 24-16 37l-28 7v36l28 7c3 13 9 26 16 37l-15 25 25 25 25-15c11 7 24 13 37 16l7 28h36l7-28c13-3 26-9 37-16l25 15 26-25-16-25c8-11 13-24 16-37z" data-original="#27A2DB"/><circle cx="327.1" cy="322" r="89.8" fill="#e1e6e9" data-original="#E1E6E9"/><circle cx="327.1" cy="322" r="51.3" fill="#1c75a1" class="active-path" data-old_color="#1C75A1" data-original="#1C75A1"/><g fill="#3a556a"><path class="api-text-anim" d="M69 173l-6 14H51l29-65h12l28 65h-11l-7-14H69zm29-11l-12-27-12 27h24zM174 128c4 3 7 9 7 17s-3 14-7 18c-5 3-12 5-22 5h-11v19h-11v-65h22c10 0 17 2 22 6zm-8 27c2-3 3-6 3-11 0-4-1-7-4-9s-7-3-13-3h-11v26h12c7 0 11-1 13-3zM194 122h11v65h-11v-65z" data-original="#3A556A"/></g><path fill="#e1e6e9" d="M347 50H200c-7 0-13-6-13-13s6-12 13-12h147c7 0 13 5 13 12s-6 13-13 13z" data-original="#E1E6E9"/></svg>
	</div>

	<h1>API Example</h1>
</div>

<h5>To get results in JSON format, you can visit:</h5>

<%= link_to *[render_results_url(5)] * 2, class: 'link', 'data-content': render_results_url(5) %>
<br>Or<br>
<%= link_to *[render_results2_url(5)] * 2, class: 'link', 'data-content': render_results2_url(5) %>

<h5>For example, in a sample Ruby program:</h5>

<div class="shadowed">
	<pre class="code"><%= example_code(render_results_url(rand(5..10))) %></pre>
</div>

<br>

<p>
	The digit specifies the number of digit the returned Pi has after decimal.
	The value specifies the value of Pi upto the given precision.
	The time specifies the time the server spent calculating Pi!
</p>

app/views/index/calculate.js.erb
$('#go').attr('data-content', 'Go').css('opacity', '1')
$('#puts').val('<%= @str %>')
showNotification('Calculated in <%= @time %> sec')

app/views/index/error_calculate.js.erb
$('#go').attr('data-content', 'Go').css('opacity', '1')
showNotification('Timed out after <%= @timeout %> sec')

app/views/index/home.html.erb
<div class="centrify mb-4">
	<div class="logo">
		<svg class="pi-anim" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><g paint-order="markers fill stroke"><path fill="#55f" d="M103 20.8h18.5V6.5H45.2c-25.8 0-35 10.5-38.7 21l4.8 4c7.8-5.9 8.5-9.2 28.2-10.3l-5.4 55.5c-1.6 14.6-13.6 21.8-17.2 28.7s6.4 16.1 17.2 16.1c6.3 0 11-5.8 12.3-17l8.2-83.7H88L80.6 97c-1.7 14.4 2.8 24.5 15.4 24.5 10.4 0 20.5-6.4 21.4-23.6H111s-2.2 9.2-8.6 10.1c-3.9.5-7.7-2.4-6.6-13.9z"/><path class="slide-up-down" fill="#fff" d="M93.4 59.3a1.7 1.7 0 01-.2 0 1.8 1.8 0 01-1.5-1.9l.9-9.5a1.8 1.8 0 013.5.4l-1 9.5a1.8 1.8 0 01-1.7 1.5z"/><path fill="#fff" d="M32.8 13.5c-.5 2-2 3.5-4 4 2 .4 3.5 2 4 3.9.4-2 1.9-3.5 3.8-4-1.9-.5-3.4-2-3.8-4z" class="spark-2"/><path class="spark-1" fill="#fff" d="M25.6 7.2zm0 2.4c-.4 2-2 3.4-3.8 4 1.9.4 3.4 2 3.8 3.8.4-2 2-3.4 3.9-4-2-.4-3.4-2-3.9-3.8zm0 10.2z" class="spark4"/></g></svg>
	</div>

	<h1>Pi Calculator</h1>
</div>

<%= form_tag calculate_path, { method: 'patch', remote: true, id: 'mainForm', class: 'form-group width-100' } do %>
	<div class="row">
		<div class="col-md-10">
			<%= number_field_tag :digits, params[:digits], min: 1, step: 1, value: 100, id: 'numberField', class: 'form-control input-sm', autocomplete: 'off', required: true %>
		</div>

		<div class="col-md-2">
			<label id="go" class="btn-outline-dark-animated btn-80" data-content="GO" onclick="wait()">
				<%= submit_tag '', name: nil, style: 'display: none' %>
			</label>
		</div>
	</div>
<% end %>

<textarea class="form-control mb-4" name="puts" id="puts" rows="10" placeholder="Enter a value above to get the value of pi"></textarea>

<div class="centrify">
	<button class="btn-outline-primary-animated btn-80" data-content="copy" id="copy" onclick="copy()"></button>
</div>

app/views/index/system_stats.html.erb
<div id="systemStatsPage" style="display: none"></div>

<div class="centrify mb-4">
	<div class="logo">
		<svg class="pi-anim" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="#00c1fd" d="M256 512A254 254 0 010 256 254 254 0 01256 0a254 254 0 01256 256 254 254 0 01-256 256z" data-original="#00C1FD"/><path fill="#08a8ee" d="M437 75C389 27 324 0 256 0v512a254 254 0 00256-256c0-68-27-133-75-181z" data-original="#08A8EE"/><g fill="#e4f7ff"><path class="info-i" d="M301 371V221H191v30h20v120h-21v30h130v-30zM256 191a45 45 0 100-90 45 45 0 000 90z" data-original="#E4F7FF"/></g><path class="info-i2" fill="#cbedfd" d="M256 191a45 45 0 000-90v90zM301 371V221h-45v180h64v-30z" class="active-path" data-old_color="#CBEDFD" data-original="#CBEDFD"/></svg>
	</div>

	<h1>System Stats</h1>
</div>

<div class="centrify" style="flex-direction: column">
	<h5>
		<%= image_tag 'ruby.svg', style: 'height: 30px ; display: inline-block' %>
		Information provided by <a target="_blank" rel="noopener" href="https://github.com/souravgoswami/linux_stat">LinuxStat</a>
		(v<%= LS::VERSION %>)
	</h5>

	<% if Rails.env.production? %>
		<h6>Warning! A production app could run in a container</h6>
	<% end %>
</div>
<hr>

<h4>OS</h4>
<div id="os"><%= render 'stats/os' %></div>
<hr>

<h4>Processor</h4>
<%= LS::CPU.model %>
<br>
Thread: <strong><%= LS::CPU.count %></strong>
<br>
Online Cores: <span id="cpuOnln"><%= render 'stats/cpu_onln' %></span>
<br>
Offline Cores: <span id="cpuOfln"><%= render 'stats/cpu_ofln' %></span>
<hr>

<h4>CPU Usages</h4>
<div id="cpuUsages">
	<%= render 'stats/cpu_usage' %>
</div>
<br>
Times: <span id="cpuTime"><%= render 'stats/cpu_time' %></span>
<hr>

<h4>Memory</h4>
<div id="memory"><%= render 'stats/memory' %></div>
<hr>

<h4>Swap</h4>
<div id="swap"><%= render 'stats/swap' %></div>
<hr>

<h4>Filesystem</h4>
<div id="filesystem"><%= render 'stats/filesystem' %></div>
<hr>

<h4>Kernel</h4>
<div id="kernel"><%= render 'stats/kernel' %></div>
<hr>

<h4>Process Info</h4>
<div id="processInfo"><%= render 'stats/processinfo' %></div>
<hr>

<h4>Processes <span id="process_counter"><%= render 'stats/process_counter'%></span></h4>
<div id="processes" class="scroll-area"><%= render 'stats/processes' %></div>
Last PID: <strong><span id="lastPID"><%= render 'stats/last_pid' %></span></strong>
<hr>

<h4>Net Usage</h4>
<div id="netUsage"><%= render 'stats/net_usage' %></div>
<hr>

<h4>Users</h4>
<div id="users"><%= render 'stats/users' %></div>
<hr>

<h4>USB Devices <span id="usbCounter"><%= render 'stats/usb_counter' %></span></h4>
<div id="usb" class="scroll-area"><%= render 'stats/usb' %></div>
<hr>

<h4>PCI Devices <span id="pciCounter"><%= render 'stats/pci_counter' %></span></h4>
<div id="pci" class="scroll-area"><%= render 'stats/pci' %></div>
<hr>

<h4>Thermal Zone</h4>
<div id="thermal" class="scroll-area"><%= render 'stats/thermal' %></div>
<hr>

<h4>Uptime</h4>
<div id="uptime"><%= render 'stats/uptime' %></div>
<hr>

<h4>Date & Time</h4>
<div id="datetime"><%= render 'stats/datetime' %></div>
<hr>

app/views/index/system_stats.js.erb
$('#os').html("<%= j render('stats/os') %>")
$('#cpuTime').html("<%= j render('stats/cpu_time') %>")
$('#cpuOnln').html("<%= j render('stats/cpu_onln') %>")
$('#cpuOfln').html("<%= j render('stats/cpu_ofln') %>")
$('#cpuUsages').html("<%= j render('stats/cpu_usage') %>")
$('#memory').html("<%= j render('stats/memory') %>")
$('#swap').html("<%= j render('stats/swap') %>")
$('#filesystem').html("<%= j render('stats/filesystem') %>")
$('#processInfo').html("<%= j render('stats/processinfo') %>")
$('#process_counter').html("<%= j render('stats/process_counter') %>")
$('#processes').html("<%= j render('stats/processes') %>")
$('#lastPID').html("<%= j render('stats/last_pid') %>")
$('#netUsage').html("<%= j render('stats/net_usage') %>")
$('#usbCounter').html("<%= j render('stats/usb_counter') %>")
$('#usb').html("<%= j render('stats/usb') %>")
$('#pciCounter').html("<%= j render('stats/pci_counter') %>")
$('#pci').html("<%= j render('stats/pci') %>")
$('#thermal').html("<%= j render('stats/thermal') %>")
$('#uptime').html("<%= j render('stats/uptime') %>")
$('#datetime').html("<%= j render('stats/datetime') %>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Pi Calculator</title>
		<meta name="viewport" content="width=device-width,initial-scale=1.0">

		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>
		<%= seo_tags(image_url('pi.png')) %>
		<%= favicon_link_tag 'pi.png' %>

		<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= stylesheet_link_tag 'btn_outline_animated', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
	</head>

	<body>
		<div class="center">
			<div class="container p-3">
				<div class="jumbotron jumbotron-bg">
					<%= yield %>
					<div id="notification"></div>

					<div class="centrify mb-4 no-select">
						<% unless current_page?(api_example_path) %>
							<%= link_to api_example_path do %>
								<%= image_tag 'api.svg', class: 'icon icon16', 'data-toggle': 'tooltip', 'data-placement': 'bottom', title: 'API Guide' %>
							<% end %>
						<% else %>
							<%= link_to root_path do %>
								<%= image_tag 'home.svg', class: 'icon icon16', 'data-toggle': 'tooltip', 'data-placement': 'bottom', title: 'Home' %>
							<% end %>
						<% end %>

						<%= link_to 'https://github.com/Souravgoswami/rails_pi' do %>
							<%= image_tag 'github.svg', class: 'icon icon16', 'data-toggle': 'tooltip', 'data-placement': 'bottom', title: 'Github' %>
						<% end %>

						<% unless current_page?(system_stats_path) %>
							<%= link_to system_stats_path do %>
								<%= image_tag 'info.svg', class: 'icon icon16', 'data-toggle': 'tooltip', 'data-placement': 'bottom', title: 'System Stats' %>
							<% end %>
						<% else %>
							<%= link_to root_path do %>
								<%= image_tag 'home.svg', class: 'icon icon16', 'data-toggle': 'tooltip', 'data-placement': 'bottom', title: 'Home' %>
							<% end %>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</body>
</html>

app/views/stats/_cpu_ofln.html.erb
<%= LS::CPU.offline.then { |x| x.empty? ? 'None'.freeze : x.join(', '.freeze) } %>

app/views/stats/_cpu_time.html.erb
<table class="styled">
	<thead>
		<tr>
			<th>CPU</th>
			<th>User</th>
			<th>Nice</th>
			<th>System</th>
			<th>Idle</th>
			<th>IO Wait</th>
			<th>IRQ</th>
		</tr>
	</thead>

	<tbody>
		<% LS::CPU.times.each_with_index do |x, i| %>
			<tr>
				<%= render 'stats/cpu_time_template', x: x, i: i %>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/stats/_cpu_time_template.html.erb
<td><%= i == 0 ? "Total" : sprintf("%d - %s", i, x[:cpu]) %></td>
<td><%= "%04.2fs" % x[:user] %></td>
<td><%= "%04.2fs" % x[:nice] %></td>
<td><%= "%04.2fs" % x[:system] %></td>
<td><%= "%04.2fs" % x[:idle] %></td>
<td><%= "%04.2fs" % x[:iowait] %></td>
<td><%= "%04.2fs" % x[:irq] %></td>

app/views/stats/_datetime.html.erb
<%= Time.now.strftime('%B %d, %A, %H:%M:%S:%2N %p') %>

app/views/stats/_kernel.html.erb
Release: <strong><%= LS::Kernel.release %></strong>
<br>
Build Date: <strong><%= LS::Kernel.build_date %></strong>
<br>
Ticks: <strong><%= LS::Sysconf.sc_clk_tck %></strong>

app/views/stats/_last_pid.html.erb
<%= LS::Process.last_pid %>

app/views/stats/_net_usage.html.erb
<table class="styled">
	<thead>
		<th>Total Download</th>
		<th>Total Upload</th>
		<th>Current Download</th>
		<th>Current Upload</th>

	</thead>

	<tbody>
		<tr>
			<% net_usage.each do |x| %>
				<td><%= x %></td>
			<% end %>
		</tr>
	</tbody>
</table>

app/views/stats/_pci_counter.html.erb
(<%= LS::PCI.count.to_i %>)

app/views/stats/_process_counter.html.erb
(<%= LS::Process.count %>)

app/views/stats/_processes.html.erb
<strong><%= LS::Process.names.values.tap(&:sort!).join(', '.freeze) %></strong>

app/views/stats/_swap.html.erb
<%= swap_usage %>

app/views/stats/_uptime.html.erb
<%= uptime %>

app/views/stats/_usb_counter.html.erb
(<%= LS::USB.count.to_i %>)

app/views/stats/_users.html.erb
Users: <strong><%= LS::User.list.join(', '.freeze) %></strong>
<br>
<br>

Username: <strong><%= LS::User.get_user %></strong>
<br>
IDs: UID: <strong><%= LS::Sysconf.get_uid %></strong> | GID: <strong><%= LS::Sysconf.get_gid %></strong> | EUID: <strong><%= LS::Sysconf.get_euid %></strong>
<br>
Home: <strong><%= LS::User.home_by_gid %></strong>